version: '3'

services:
  web:
    
    container_name: APACHE
    
    image: lavoweb/php-7.2
    
    ports:
      - "8001:80"
    
    volumes:
      - ./src:/var/www/html
    
    links:
      - mysql_db:db
  
  mysql_db:

    container_name: MYSQL
    
    image: mysql:5.5
    
    volumes:
      - ~/mysql:/var/lib/mysql
    
    ports:
      - "3306:3306"
    
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_USER: root
        MYSQL_DATABASE: projet1_stages
  
  phpmyadmin:
    
    container_name: P_M_A
    
    image: phpmyadmin/phpmyadmin
    
    ports:
      - "8080:80"
    
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    links:
      - mysql_db:db